#数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ddd?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

#logging.file.name=labour-project1.log
#logging.config=classpath:logback-spring.xml
#mybatis.configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#mybatis.mapper-locations=classpash:mapper/*.xml


mybatis-plus:
  mapper-locations: classpash:mapper/*.xml
